#####################
#      VOLUMES      #
#####################
volumes:
  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      device: /home/${USER}/data/wordpress
      type: none
      o: bind

  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      device: /home/${USER}/data/mysql
      type: none
      o: bind

#####################
#     SERVICES      #
#####################
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_vol:/var/www/html
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file: .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wordpress_vol:/var/www/html
    restart: always
    networks:
      - inception
    env_file: .env

  redis:
    container_name: redis
    depends_on:
      - wordpress
    build: ./requirements/bonus/redis
    image: redis
    volumes:
      - wordpress_vol:/data
    restart: always
    networks:
      - inception

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    image: ftp
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - 21:21
      - "21100-21110:21100-21110"
    restart: always
    env_file: .env
    networks:
      - inception

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception

  website:
    container_name: website
    build: ./requirements/bonus/website
    image: website
    restart: always
    networks:
      - inception

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    networks:
      - inception

#####################
#     NETWORKS      #
#####################
networks:
  inception:
    driver: bridge
